version: "3"
services:
  product_api_task:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OFFER_BASE_URL=$OFFER_BASE_URL
      - OFFER_AUTH_CODE=$OFFER_AUTH_CODE
    image: product_api_task:latest
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:127.0.0.1"

